<?php

namespace Algo\Nums;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-04-30 at 00:48:06.
 */
class FibonacciTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Fibonacci
     */
    private $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->obj = new Fibonacci;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {

    }

    /**
     * @covers Algo\Nums\Fibonacci::calc
     * @dataProvider calcProvider
     */
    public function testCalc($num, $expected) {
        \PHPUnit\Framework\assertEquals($expected, $this->obj->calc($num));
    }

    public function calcProvider() {
        return [
            [ 0, 0 ],
            [ 1, 1 ],
            [ 2, 1 ],
            [ 3, 2 ],
            [ 4, 3 ],
            [ 5, 5 ],
            [ 6, 8 ],
            [ 7, 13 ],
            [ 8, 21 ],
            [ 9, 34 ],
            [ 10, 55 ]
        ];
    }

    /**
     * @covers Algo\Nums\Fibonacci::getLog
     * @dataProvider getLogProvider
     */
    public function testGetLog($n, $expected) {
        $this->obj->calc($n);
        \PHPUnit\Framework\assertCount($expected, $this->obj->getLog());
    }

    public function getLogProvider() {
        return [
            [ 0, 2 ],
            [ 1, 2 ],
            [ 2, 3 ],
            [ 3, 4 ],
            [ 7, 8 ],
            [ 11, 12 ],
        ];
    }
}
