<?php

namespace Algo\Nums;

use Algo\Nums\Gcd;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-04-17 at 01:06:48.
 */
class GcdTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Gcd
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {

    }

    /**
     * @covers Algo\Nums\Gcd::get
     * @dataProvider getProvider
     */
    public function testGet($a, $b, $expected) {
        $algo = new Gcd();
        $this->assertEquals($expected, $algo->calc($a, $b));
    }

    public function getProvider() {
        return [
            [ 54, 24, 6 ],
            [ 48, 18, 6 ],
            [ 99, 108, 9 ],
            [ 125, 46, 1 ],
            [ 17, 37, 1 ],
            [ 35, 42, 7 ],
            [ 72, 114, 6 ]
        ];
    }

    /**
     * @covers Algo\Nums\Gcd::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog() {
        $algo = new Gcd();
        $algo->calc(54, 24);
        $log = $algo->getLog();
        $this->assertNotEmpty($log);
        $this->assertIsArray($log);
    }

}
