<?php

namespace Algo\Nums;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-04-17 at 01:06:48.
 */
class LcmTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Lcm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {

    }


    /**
     * @covers Algo\Nums\Lcm::get
     * @dataProvider getProvider
     */
    public function testGet($a, $b, $expected) {
        $algo = new Lcm();
        $this->assertEquals($expected, $algo->calc($a, $b));
    }

    public function getProvider() {
        return [
            [ 4, 6, 12 ],
            [ 21, 6, 42 ],
            [ 16, 20, 80 ],
        ];
    }

    /**
     * @covers Algo\Nums\Gcd::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog() {
        $algo = new Lcm();
        $algo->calc(21, 6);
        $log = $algo->getLog();
        $this->assertNotEmpty($log);
        $this->assertIsArray($log);
        $this->assertCount(4, $log);
    }
}
