<?php

namespace Algo\Nums;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-04-17 at 01:06:48.
 */
class LcmTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Lcm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Lcm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {

    }


}
